# Generated by Django 4.1 on 2022-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
