# Generated by Django 4.1 on 2022-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0002_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
