# Generated by Django 4.1 on 2022-08-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0003_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('DECLINE', 'DECLINE'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=15),
        ),
    ]
