# Generated by Django 4.1 on 2022-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0008_booking_approved_booking_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
