# Generated by Django 4.1 on 2022-08-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0010_bookingslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiview.booking'),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
