# Generated by Django 4.1 on 2022-08-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0011_alter_bookingslot_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslot',
            name='booking',
        ),
    ]
