# Generated by Django 4.1 on 2022-08-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0012_remove_bookingslot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiview.booking'),
        ),
    ]
